# Generated by Django 3.2.6 on 2021-09-09 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=120)),
                ('Description', models.TextField()),
                ('Language', models.CharField(max_length=120)),
                ('Start_Time', models.DateField(default=datetime.datetime.now)),
                ('End_Time', models.DateField(default=datetime.datetime.now)),
                ('Personal_Count', models.IntegerField()),
                ('Budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Ability_Rating', models.CharField(max_length=120)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project')),
            ],
        ),
    ]
