# Generated by Django 3.2.6 on 2021-09-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectabilities',
            name='Project',
        ),
    ]
