# Generated by Django 3.2.6 on 2021-09-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projectabilities_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectabilities',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project'),
            preserve_default=False,
        ),
    ]
