# Generated by Django 3.2.6 on 2021-09-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edit', models.BooleanField()),
                ('Delete', models.BooleanField()),
                ('Add', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Surname', models.CharField(max_length=120)),
                ('Username', models.CharField(max_length=120)),
                ('Gender', models.CharField(max_length=120)),
                ('Birthday', models.DateField()),
                ('Branch', models.CharField(max_length=120)),
                ('Salary', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Graduate', models.CharField(max_length=120)),
                ('Employee_Type', models.CharField(max_length=120)),
                ('Group', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('ImageUrl', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='user.department')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='user.role')),
            ],
        ),
        migrations.CreateModel(
            name='GetInvolvedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.project')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Ability_Rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilityratings', to='user.ability_rating')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
